### ISSUE TITLE
Multiple ways of expressing the same time

### ISSUE THREAD

**Issue by ecorm** [cbor-wg/time-tag#1]
(Also posted at https://mailarchive.ietf.org/arch/msg/cbor/lxN8zxiFV2mNKLlbDYw8Ff1eFI0/)

I'm implementing tags 1001 and 1002 in my C++ library to exchange time points and durations.

I'm in the situation where I'm not sure which is the "expected" way to encode time as nanoseconds since the Unix epoch. I'm specifically referring to `std::chrono::system_clock::time_point`, which is a 64 bit integer. There are currently three ways I could encode such a value.

1. The whole number of seconds under Key 1, with the remaining nanoseconds under Key -9.

2. The total number of nanoseconds under Key -9, with a value of zero under Key 1.

3. The total number of nanoseconds expressed as a Decimal Fraction under Key 4.

Option 2 is the easiest and most efficient because it doesn't involve a division/subtraction calculation. However, a receiver that discards Key -9 will end up with zero seconds. At least with option 1, the receiver will know the number of whole seconds if Key -9 is ignored.

Option 3 requires that the sender and receiver understand Tag 4 (Decimal Fraction), or at least the concept of decimal fractions within the context of tags 1001-1003.

I'm guessing that option 1 is the "canonical" way, but I'm not entirely sure. Some guidance would be appreciated. **Perhaps a few words concerning this should be added to the standard's text?**

On the receiving side, my library would ideally handle all three scenarios. It's on the sending side I'm more concerned about when I need to interoperate with CBOR decoders other than mine.

**Comment by cabo** [comment]
Your case (3) is definitely valid.

For -3/..., the current text indeed does not limit the range of the additional part.
So your (2) would be a valid way to express the timestamp.
Except that we don't allow bignums, so you got yourself a Y2608 problem.
Any other distribution between key 1 and key -9 is also valid.
So the onus is on the receiver to put this together to a proper tv_sec/tv_nsec.
