### ISSUE TITLE
Are the clock quality fields allowed for the Duration format?

### ISSUE THREAD

**Issue by ecorm** [cbor-wg/time-tag#2]
In section [3.5. Clock Quality](https://www.ietf.org/archive/id/draft-ietf-cbor-time-tag-00.html#name-clock-quality), is says (emphasis mine):

> A number of keys are defined to indicate the quality of clock that was **used to determine the point in time**.

Due to the phrase "point in time", this leads one to believe that the quality keys are only applicable to the Time format (tag 1001).

However in section [4. Duration Format ](https://www.ietf.org/archive/id/draft-ietf-cbor-time-tag-00.html#name-duration-format), it says (emphasis mine):

> Except for using Tag 1002 instead of 1001, **durations are structurally identical to time values**.

This leads one to believe that quality keys are also permitted for tag 1002 (durations).

So there's a bit of a contradiction, and I don't know how to deal with the possibility of quality keys appearing in the Duration format.

**Comment by ecorm** [comment]
Related to this are the Uncertainty and Guarantee keys which can themselves be Duration maps. If the nested Durations embedded in the Uncertainty and Guarantee keys also have quality keys, then there can be an unbounded amount of recursion and it becomes impossible to store the overall entity in a fixed amount of storage.

**Comment by cabo** [comment]
To your second comment: "Don't do that then" :-)
Durations that are measured do have uncertainties (and possibly even guarantees).
Durations that are given as uncertainties naturally do not have uncertainties.
I wrote up a couple of notes to this effect in https://github.com/cbor-wg/time-tag/pull/16
