### ISSUE TITLE
Should clock quality be it's own tag?

### ISSUE THREAD

**Issue by ecorm** [cbor-wg/time-tag#3]
I get the impression that the extended time types are trying to be "kitchen sink" types with too much information. Most applications dealing with time don't care about the PTP clock quality stuff. I suggest that the clock quality be it's own separate tag.

Applications wanting to convey a clock quality along with an extended time can simply combine them both in an array of two elements.

Also consider the use case where the same clock quality applies to a series of time points, which I think would be more likely than a series of time points each having their own clock quality. By having the clock quality be it's own separate tag, it makes it possible for applications to exchange data structures with multiple time points having the same clock quality.

**Comment by ecorm** [comment]
> But this doesn’t take away the benefit of including time attributes inside a time, duration, or period.

It may be a benefit in terms of data compactness and having everything "together" under one map, but it ends up making things messy in my CBOR decoder where I need to store the clock quality as an optional field in the intermediate time type I use between the decoder and application time types (such as `std::chrono::time_point` or `boost::date_time`). That optional clock quality field will never be used in the vast majority of applications using my library, yet I still have to make provision for it if I want to claim that my library supports CBOR tags 1001 and 1002.

If I choose to ignore the clock quality fields and not store them in my intermediate time type, then there would be no means for (the rare) applications that actually need PTP clock quality to retrieve those values.

**Comment by cabo** [comment]
Tag 1001..1003 already are extensible, so there is no way to claim full support (as you don't know what extensions will be made in the future).  You could handle unsupported information already known in the same way you would support future unsupported information, e.g., by offering the raw CBOR information to the application.
