### ISSUE TITLE
Local time and time zones

### ISSUE THREAD

**Issue by ecorm** [cbor-wg/time-tag#4]
There's currently no standardized way of exchanging local date/times (with or without time zone information) in CBOR. I suggest that a "local" time scale be added (in addition to the existing UTC and TAI). The number of seconds for a given local date and time of day would be calculated the same way as for POSIX time (this is how it's done in C++ with `std::chrono::local_time`).

The time zone, if specified, could be a text string corresponding to the IANA tz database name (e.g. "Europe/Paris"). This would be stored in one of the unused extended time keys, such as `-10`.

A use case where a local time needs to be exchanged would be a building automation system where an event is local to the building. For example: "Turn on the Yuletide tree lights at 12:00 (local time) on December 25, 2021". Another use case might be an appointment in a planning app, where it the appointment is in local time.

It's not always true that every local date/time with timezone has a corresponding equivalent time in UTC. Local date/times can be ambiguous when they straddle a daylight saving time change. For local date/times occurring in the future, the rules for daylight saving could change. It therefore might be important for certain applications to exchange local date/times as actual local date/times without converting them to their "equivalent" UTC time.

**Comment by cabo** [comment]
> There's currently no standardized way of exchanging local date/times (with or without time zone information) in CBOR. I suggest that a "local" time scale be added (in addition to the existing UTC and TAI). The number of seconds for a given local date and time of day would be calculated the same way as for POSIX time (this is how it's done in C++ with std::chrono::local_time).

We have been waiting for the SEDATE WG to define a structure for timezone information; that could be added to the time attributes.
Please see https://www.ietf.org/archive/id/draft-ietf-sedate-datetime-extended-01.html for the pre-IETF112 revision, or https://github.com/ietf-wg-sedate/draft-ietf-sedate-datetime-extended for more recent pull requests.
We’ll have the same problem as SEDATE in that we might have actual time values as well as calendaring information that becomes fixed on the timescale only after  the event.

> The time zone, if specified, could be a text string corresponding to the IANA tz database name (e.g. "Europe/Paris"). This would be stored in one of the unused extended time keys, such as -10.

Exactly; the plan would be to make sure that this and all other SEDATE extensions can live in a time tag.

> A use case where a local time needs to be exchanged would be a building automation system where an event is local to the building. For example: "Turn on the Yuletide tree lights at 12:00 (local time) on December 25, 2021". Another use case might be an appointment in a planning app, where it the appointment is in local time.

There also is the "floating time” concept, please see the brief discussion at the end of https://ietf-wg-sedate.github.io/draft-ietf-sedate-datetime-extended/scope/draft-ietf-sedate-datetime-extended.html#name-scope

> It's not always true that every local date/time with timezone has a corresponding equivalent time in UTC.

(Or it could have two: A/B times during a clock fallback.)

> Local date/times can be ambiguous when they straddle a daylight saving time change. For local date/times occurring in the future, the rules for daylight saving could change. It therefore might be important for certain applications to exchange local date/times as actual local date/times without converting them to their "equivalent" UTC time.

Indeed; what SEDATE have been discussing is enabling the provision of both the UTC offset and the timezone name; plus information which of the two wins.
RFC 3339 datetimes would have the UTC offset win, while calendaring times would have the timezone name win (with potential A/B disambiguation by the offset or maybe some other means).
Waiting for SEDATE to make up its mind is what holds up completing the present tag definition, even though parts of it are already in use in applications.

Grüße, Carsten

**Comment by ecorm** [comment]
@cabo , are you aware of the [revised string persistence syntax of the proposed ECMAScript Temporal](https://tc39.es/proposal-temporal/docs/index.html#string-persistence)? At quick glance, it seems to match the syntax proposed in SEDATE.

**Comment by cabo** [comment]
Yes, the SEDATE WG was created to specifically look at Temporal and other specification proposals.

**Comment by cabo** [comment]
As we now have keys -10 and 10 (Time Zone Hint), I believe this item is covered.

We do not have an exact equivalent of RFC 3339 time offsets, but that is actually rarely desirable.
The actual timestamp in a time-tag is always timescale-referenced.
Giving an absolute time-offset is rarely what is actually needed; if we ever come across such a case, we can add to the Map Key registry.

**Comment by ecorm** [comment]
Thank you for your work on this matter, and on Internet standards in general. :+1: 

There remains the use case of a local time in an unspecified time zone (which is represented as `std::chrono::local_time` in C++). I checked the TZ database to see if there's an entry that represents "unspecified time zone", but could only find "Factory" which is defined as UTC+0.

Transmitting local time in an unspecified time zone doesn't seem to be much in demand, so I won't insist on its inclusion in the CBOR 1001 time tag. Perhaps I'll propose a new, separate tag for that purpose. It could be useful for constrained IoT devices with a real time clock, but lacking the non-volatile memory needed for a timezone database.
